title: CloudYuga
description: We provide trainings in Docker, Kubernetes, Mesos Marathon, Container Security, GO Language, Advance Linux Administration etc.
footer-description: We are here to help you learn and deploy cloud native application using containers. With our trainings, you would get in-depth knowledge on the subject and with our consulting services, we can guide to do the deployment.
url: "https://cloudyuga.guru"
logo: "/img/cloudyuga-logo.svg"
phone: "+91 8861001308"
email: "neependra@cloudyuga.guru"
facebook: "https://www.facebook.com/cloudyuga.guru"
twitter: "https://twitter.com/cloudyuga"
github: "https://github.com/cloudyuga/"
feed: "/feed.xml"

analytics: UA-102630530-1
disqus: cloudyuga
mailchimp: //guru.us13.list-manage.com/subscribe/post?u=e759d8392b3869df85162f2b8&id=e6f0938d13

permalink: "/blog/:title/"

paginate: 9
paginate_path: "/blog/all/page:num/"


collections:
    trainings:
        output: true
        permalink: "/trainings/:title/"
    webinars:
        output: true
        permalink: "/webinars/:title/"
    consulting:
        output: true
        permalink: "/consulting/:title/"
    careers:
        output: true
        permalink: "/careers/:title/"

future: true

exclude:
    - .sass-cache

include:
    - _pages

sass:
 style: compressed


#compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []




authors:
      Neependra:
        display_name: Neependra
        about: Founder and Principal Consultant
        email: mailto:neependra@cloudyug.guru
        facebook: https://www.facebook.com/neependra.khare
        linkedin: https://www.linkedin.com/in/neependra
        twitter: https://twitter.com/neependra
        avatar: /img/neependra-khare.jpg

      Shiju:
        display_name: Shiju
        about: Principal Consultant
        email: mailto:gophermonk@gmail.com
        facebook: https://www.facebook.com/shijuvar
        linkedin: https://www.linkedin.com/in/shijuvar
        twitter: https://twitter.com/shijucv
        avatar: /img/Shiju-Varghese.png

      sumit:
        display_name: Sumit Murari
        about: Senior Consultant
        email: mailto:sumit@cloudyuga.guru
        linkedin: https://linkedin.com/in/murarisumit
        avatar: /img/sumit-murari.jpg
        website: https://sumit.murari.me

      vishal:
        display_name: Vishal Ghule
        about: Software Engineer
        email: mailto:vishal@cloudyuga.guru
        linkedin: https://linkedin.com/in/vishal-ghule
        twitter: https://twitter.com/thevishalghule
        avatar: /img/vishal-ghule.jpg

plugins:
    - jekyll-seo-tag
    - jekyll-redirect-from
    - jekyll-sitemap
    - jekyll-paginate
